/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'quantity' : bigint, 'perfumeId' : bigint }
export interface Order {
  'user' : Principal,
  'items' : Array<CartItem>,
  'totalPrice' : bigint,
}
export interface Perfume {
  'id' : bigint,
  'tagline' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : bigint,
  'scentNotes' : Array<string>,
}
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'getAllPerfumes' : ActorMethod<[], Array<Perfume>>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getPerfumeById' : ActorMethod<[bigint], Perfume>,
  'placeOrder' : ActorMethod<[], undefined>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];