/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Perfume = IDL.Record({
  'id' : IDL.Nat,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'scentNotes' : IDL.Vec(IDL.Text),
});
export const CartItem = IDL.Record({
  'quantity' : IDL.Nat,
  'perfumeId' : IDL.Nat,
});
export const Order = IDL.Record({
  'user' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllPerfumes' : IDL.Func([], [IDL.Vec(Perfume)], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPerfumeById' : IDL.Func([IDL.Nat], [Perfume], ['query']),
  'placeOrder' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Perfume = IDL.Record({
    'id' : IDL.Nat,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'scentNotes' : IDL.Vec(IDL.Text),
  });
  const CartItem = IDL.Record({ 'quantity' : IDL.Nat, 'perfumeId' : IDL.Nat });
  const Order = IDL.Record({
    'user' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Nat,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllPerfumes' : IDL.Func([], [IDL.Vec(Perfume)], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPerfumeById' : IDL.Func([IDL.Nat], [Perfume], ['query']),
    'placeOrder' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };